apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-spring-deployment
  #namespace: tomcat-spring-namespace
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: nadiaaguerbaoui1/tomcat-spring-image:latest
        ports:
        - containerPort: 8081
---        
apiVersion: v1
kind: Service
metadata:
  #name: tomcat-spring-service
  namespace: tomcat-spring-namespace
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
      nodePort: 32222